### ISSUE TITLE
Print statement not supported in python version 3.2 or higher

### ISSUE THREAD

**Issue by andriconda** [csark/isp-checkup#1]
The print statements in file isp_checkup.py do not work with python versions 3.2 and higher.

Occurrences-
line 12:     `print 'Test Running....'`
line 66:     `print 'Test Complete'`

Fix:
line 12:     `print('Test Running....')`
line 66:     `print ('Test Complete')`

**Comment by csark** [comment]
Hey thanks for pointing that out. This is still really rough and I am trying to get it set up right but you input helps. I have fixed this issue.
